spring.application.name=quiz-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quizProjectDb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:713143}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8082

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
#eureka configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=127.0.0.1
#eureka.instance.hostname=127.0.0.1


# Circuit Breaker config
#resilience4j.circuitbreaker.instances.questionService.sliding-window-size=10
#resilience4j.circuitbreaker.instances.questionService.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.questionService.wait-duration-in-open-state=10s
#resilience4j.circuitbreaker.instances.questionService.permitted-number-of-calls-in-half-open-state=3
#resilience4j.circuitbreaker.instances.questionService.automatic-transition-from-open-to-half-open-enabled=true

# What each setting means:
# sliding-window-size=10        → track last 10 requests
# failure-rate-threshold=50     → if 50% fail → OPEN circuit
# wait-duration-in-open-state   → wait 10s before trying again
# permitted-calls-in-half-open  → try 3 requests to test recovery

# Enable circuit breaker for Feign clients
spring.cloud.openfeign.circuitbreaker.enabled=true

jwt.secret=dGhpc2lzYXZlcnlzdHJvbmdzZWNyZXRrZXlmb3JqV1QyMDI0YXBwbGljYXRpb24=
