spring.application.name=service-registary



# Port where Eureka Server will run
server.port=8761

# Eureka server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Hostname (optional, useful if running on a specific machine)

eureka.instance.prefer-ip-address=true

eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1


